# Generated by Django 4.2.4 on 2023-08-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtor',
            new_name='Produto',
        ),
    ]
