# Generated by Django 4.2.4 on 2023-08-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variacao', 'verbose_name_plural': 'Variações'},
        ),
    ]
